modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://example.invalid/neko_fix"

[[mods]]
modId = "neko_fix"
version = "1.0.12"
displayName = "Neko Fix"
authors = "Neko_Fix"
description = '''
Fixes JustARod screen background blur, first-person legs with Better Combat,
and toNeko sleeping flicker.
'''

[[dependencies.neko_fix]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.248,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.neko_fix]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.neko_fix]]
modId = "justarod"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.neko_fix]]
modId = "toneko"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.neko_fix]]
modId = "playeranimator"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "neko_fix.mixins.json"
